# @url = 
@url = http://localhost:3000

###
GET {{url}}/showMovies

###
GET {{url}}/showMoviesPopularity

### 
GET {{url}}/showMoviesNewest

###
GET {{url}}/showUpcoming

###
GET {{url}}/searchByGenre

###
GET {{url}}/searchByTitle?title=harry

###
GET {{url}}/searchById?id=697064